version: '3.2'

volumes:
  prometheus:

networks:
  traefik-net:
    external: true
  monitoring:
    driver: overlay
    attachable: true

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus:/prometheus
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      #- ./configs/alert.rules:/etc/prometheus/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=https://prometheus.4labs.example'
    ports:
      - '9090:9090'
    networks:
      - monitoring
      - traefik-net
    deploy:
      labels:
        - traefik.port=9090
        - traefik.frontend.rule=Host:prometheus.4labs.example
        - traefik.backend=prometheus
        - traefik.docker.network=traefik-net
      placement:
        constraints: [node.role == manager]

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 32M
    hostname: "{{.Node.ID}}"
    environment:
      HOST_HOSTNAME: /etc/hostname
    networks:
      - monitoring

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 364M
    networks:
      - monitoring
